spring:
  application:
    name: myMicroSvc
  cloud:
    consul:
      host: ${CONSUL:localhost}
      port: 8500
      #To disable the Consul Discovery Client
      enabled: true
      discovery:
        tags: foo=bar
        #For TLS update http to https in scheme
        scheme: https
        healthCheckPath: /status
#        healthCheckUrl: ${req.protocol}://localhost:${server.port}${spring.cloud.consul.discovery.healthCheckPath}
        healthCheckInterval: 10s
        #To disable the service registration
        register: true
        instanceId: ${spring.application.name}:${random.value}

management:
  health:
    consul.enabled: true

#server.port: 8443
#http.port: 8081
#req.protocol: http

#server.ssl:
#  key-store-type: JKS
#  key-store: classpath:keystore/ssl-cert.jks
#  key-store-password: changeit
#  key-password: changeit
#  enabled: true

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    com.tdcr.consul: INFO
  file: logs/ServiceDiscovery.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: