#configuration read from consul

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    com.tdcr.consul: INFO
  file: logs/ServiceDiscovery.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: ""